---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: Infrastructure/xld-smoke-test
  children:
  - name: localhost
    type: overthere.LocalHost
    os: UNIX
    children:
    - name: test runner
      type: smoketest.Runner
