language: java
notifications:
  slack:
    secure: ehnnVyHDDVzhlFOZJ9oBRcenf0k4Co8T7Cr7TdZ6N/vJZ4M2BKw/hlZsiU+2NI6qigh62KDGy8HNsZmKAvKqjdJ/xwcAreyt7+gbua0ahFPJkzNm8XzZpU4ryBdSNWZd3g7SxIFTENq82+X6JytNn+Dm0ftRM2+rduHiVQgCg8k=
deploy:
  provider: releases
  api_key:
    secure: Wev3Vj3tHtD1a8KYDT8af6WRCyZeNeUTXAqBfXLlSeLXGRmjm0+YWmLc0CWSPMb6ZvHnegUuleN6aKFU3SEcUqtBPiy2ZLxMpz5PdJvWWCP2z/ecPmow55F817g7VY7VS6PfJiUSWElN7EnXPdzEN+JHBHZFUh6i27I4ltBEFbA=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-smoke-test-plugin
    all_branches: true
    tags: true
