language: java
notifications:
  hipchat:
    rooms:
      secure: TYbMuXiro85Mpp4MkGsHqkn/0vGHBcKj3FY2wSEuxLFIr38/OobCtK4ECpX2eFKdZxi+qeudryX5gYrXbbRSklSY3a5hPKt5FVDnIo3i54XhocmC+trkWR/mq0674o6o2YUsWkOTm6smM5B1TQngMD29XEui36TsNPpR18j0bxQ=
deploy:
  provider: releases
  api_key:
    secure: Wev3Vj3tHtD1a8KYDT8af6WRCyZeNeUTXAqBfXLlSeLXGRmjm0+YWmLc0CWSPMb6ZvHnegUuleN6aKFU3SEcUqtBPiy2ZLxMpz5PdJvWWCP2z/ecPmow55F817g7VY7VS6PfJiUSWElN7EnXPdzEN+JHBHZFUh6i27I4ltBEFbA=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-smoke-test-plugin
    all_branches: true
    tags: true
