language: java
notifications:
  hipchat:
    rooms:
      secure: TYbMuXiro85Mpp4MkGsHqkn/0vGHBcKj3FY2wSEuxLFIr38/OobCtK4ECpX2eFKdZxi+qeudryX5gYrXbbRSklSY3a5hPKt5FVDnIo3i54XhocmC+trkWR/mq0674o6o2YUsWkOTm6smM5B1TQngMD29XEui36TsNPpR18j0bxQ=
deploy:
  provider: releases
  api_key:
    secure: VcwxOdFebF5FcOCBMiUB3HFUfoTdVOd6ExlMPIzQXv6XxOiCtlkwKbB9iuKJ7FnbMya4r3bCwuCzf9j4PZ3w/OEvV65e9aOKK0v6svVfHq2RxNV3x6BSe4mOEwT679GAZJ/pEKr34gQk0Gcc1n/G6e9hx+K3PuK9eOjZ55Ui+w0=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-smoke-test-plugin
    all_branches: true
    tags: true
