language: java
notifications:
  hipchat:
    rooms:
      secure: TYbMuXiro85Mpp4MkGsHqkn/0vGHBcKj3FY2wSEuxLFIr38/OobCtK4ECpX2eFKdZxi+qeudryX5gYrXbbRSklSY3a5hPKt5FVDnIo3i54XhocmC+trkWR/mq0674o6o2YUsWkOTm6smM5B1TQngMD29XEui36TsNPpR18j0bxQ=
deploy:
  provider: releases
  api_key:
    secure: VjIWWI6m4xRdIPLwfuEdU/P3wx8YzbQP3ioBM0VjlXep99+GhGI4foAwYhYSVOY4lkNtlauw9kCFzlFFxOoa80MmGf2oMsAIvgdVPPtNLv+IlzGLx2/R1di7Vt5Q9JWOcvbZoKUeynFch9j1oEBO5HmrOHUL4gEzdcwSqItfVcw=
  file_glob: true
  file: build/distributions/*
  on:
    repo: xebialabs-community/xld-smoke-test-plugin
    all_branches: true
    tags: true
